package teamkyr.pokemon;

/*
  1: Monster
  2: Water 1
  3: Bug
  4: Flying
  5: Field
  6: Fairy
  7: Grass
  8: Human-Like
  9: Water 3
  10: Mineral
  11: Amorphous
  12: Water 2
  13: Dragon
   */
public class Pokedexes {
    //SV dex base game
    public static final String SV_DEX = "SVdex";
    public static final String SVDLC_DEX = "SVDLCdex";
    public static Pokemon[] getDex(String dexName) {

        switch (dexName) {
            case SV_DEX:
                return Pokedexes.SVdex;
            case SVDLC_DEX:
                return Pokedexes.SVDLCdex;
            default:
                return null;
        }
    }
    private static final Pokemon[] SVdex = {
            new Pokemon("Floragato","Field","Grass",87.5,20),
            new Pokemon("Meowscarada","Field","Grass",87.5,20),
            new Pokemon("Fuecoco","Field",87.5,20),
            new Pokemon("Crocalor","Field",87.5,20),
            new Pokemon("Skeledirge","Field",87.5,20),
            new Pokemon("Quaxly","Flying","Water 1",87.5,20),
            new Pokemon("Quaxwell","Flying","Water 1",87.5,20),
            new Pokemon("Quaquaval","Flying","Water 1",87.5,20),
            new Pokemon("Lechonk","Field",50.0,15),
            new Pokemon("Oinkologne","Field",100.0,15),
            new Pokemon("Tarountula","Bug",50.0,15),
            new Pokemon("Spidops","Bug",50.0,15),
            new Pokemon("Nymble","Bug",50.0,20),
            new Pokemon("Lokix","Bug",50.0,20),
            new Pokemon("Hoppip","Fairy","Grass",50.0,20),
            new Pokemon("Skiploom","Fairy","Grass",50.0,20),
            new Pokemon("Jumpluff","Fairy","Grass",50.0,20),
            new Pokemon("Fletchling","Flying",50.0,15),
            new Pokemon("Fletchinder","Flying",50.0,15),
            new Pokemon("Talonflame","Flying",50.0,15),
            new Pokemon("Pawmi","Field",50.0,15),
            new Pokemon("Pawmo","Field",50.0,15),
            new Pokemon("Pawmot","Field",50.0,15),
            new Pokemon("Houndour","Field",50.0,20),
            new Pokemon("Houndoom","Field",50.0,20),
            new Pokemon("Yungoos","Field",50.0,15),
            new Pokemon("Gumshoos","Field",50.0,15),
            new Pokemon("Skwovet","Field",50.0,20),
            new Pokemon("Greedent","Field",50.0,20),
            new Pokemon("Sunkern","Grass",50.0,20),
            new Pokemon("Sunflora","Grass",50.0,20),
            new Pokemon("Kricketot","Bug",50.0,15),
            new Pokemon("Kricketune","Bug",50.0,15),
            new Pokemon("Scatterbug","Bug",50.0,15),
            new Pokemon("Spewpa","Bug",50.0,15),
            new Pokemon("Vivillon","Bug",50.0,15),
            new Pokemon("Combee","Bug",87.5,15),
            new Pokemon("Vespiquen","Bug",-100.0,15),
            new Pokemon("Rookidee","Flying",50.0,15),
            new Pokemon("Corvisquire","Flying",50.0,15),
            new Pokemon("Corviknight","Flying",50.0,15),
            new Pokemon("Happiny","Undiscovered",-100.0,40),
            new Pokemon("Chansey","Fairy",-100.0,40),
            new Pokemon("Blissey","Fairy",-100.0,40),
            new Pokemon("Azurill","Undiscovered",25.0,10),
            new Pokemon("Marill","Water 1","Fairy",50.0,10),
            new Pokemon("Azumarill","Water 1","Fairy",50.0,10),
            new Pokemon("Surskit","Water 1","Bug",50.0,15),
            new Pokemon("Masquerain","Water 1","Bug",50.0,15),
            new Pokemon("Buizel","Water 1","Field",50.0,20),
            new Pokemon("Floatzel","Water 1","Field",50.0,20),
            new Pokemon("Wooper","Water 1","Field",50.0,20),
            new Pokemon("Clodsire","Water 1","Field",50.0,20),
            new Pokemon("Psyduck","Water 1","Field",50.0,20),
            new Pokemon("Golduck","Water 1","Field",50.0,20),
            new Pokemon("Chewtle","Monster","Water 1",50.0,20),
            new Pokemon("Drednaw","Monster","Water 1",50.0,20),
            new Pokemon("Igglybuff","Undiscovered",25.0,10),
            new Pokemon("Jigglypuff","Fairy",25.0,10),
            new Pokemon("Wigglytuff","Fairy",25.0,10),
            new Pokemon("Ralts","Human-Like","Amorphous",50.0,20),
            new Pokemon("Kirlia","Human-Like","Amorphous",50.0,20),
            new Pokemon("Gardevoir","Human-Like","Amorphous",50.0,20),
            new Pokemon("Gallade","Human-Like","Amorphous",100.0,20),
            new Pokemon("Drowzee","Human-Like",50.0,20),
            new Pokemon("Hypno","Human-Like",50.0,20),
            new Pokemon("Gastly","Amorphous",50.0,20),
            new Pokemon("Haunter","Amorphous",50.0,20),
            new Pokemon("Gengar","Amorphous",50.0,20),
            new Pokemon("Tandemaus","Field","Fairy",0,10),
            new Pokemon("Maushold","Field","Fairy",0,10),
            new Pokemon("Pichu","Undiscovered",50.0,10),
            new Pokemon("Pikachu","Field","Fairy",50.0,10),
            new Pokemon("Raichu","Field","Fairy",50.0,10),
            new Pokemon("Fidough","Field","Mineral",50.0,20),
            new Pokemon("Dachsbun","Field","Mineral",50.0,20),
            new Pokemon("Slakoth","Field",50.0,15),
            new Pokemon("Vigoroth","Field",50.0,15),
            new Pokemon("Slaking","Field",50.0,15),
            new Pokemon("Bounsweet","Grass",-100.0,20),
            new Pokemon("Steenee","Grass",-100.0,20),
            new Pokemon("Tsareena","Grass",-100.0,20),
            new Pokemon("Smoliv","Grass",50.0,20),
            new Pokemon("Dolliv","Grass",50.0,20),
            new Pokemon("Arboliva","Grass",50.0,20),
            new Pokemon("Bonsly","Undiscovered",50.0,20),
            new Pokemon("Sudowoodo","Mineral",50.0,20),
            new Pokemon("Rockruff","Field",50.0,15),
            new Pokemon("Lycanroc","Field",50.0,15),
            new Pokemon("Rolycoly","Mineral",50.0,15),
            new Pokemon("Carkol","Mineral",50.0,15),
            new Pokemon("Coalossal","Mineral",50.0,15),
            new Pokemon("Shinx","Field",50.0,20),
            new Pokemon("Luxio","Field",50.0,20),
            new Pokemon("Luxray","Field",50.0,20),
            new Pokemon("Starly","Flying",50.0,15),
            new Pokemon("Staravia","Flying",50.0,15),
            new Pokemon("Staraptor","Flying",50.0,15),
            new Pokemon("Oricorio","Flying",25.0,20),
            new Pokemon("Mareep","Monster","Field",50.0,20),
            new Pokemon("Flaaffy","Monster","Field",50.0,20),
            new Pokemon("Ampharos","Monster","Field",50.0,20),
            new Pokemon("Petilil","Grass",-100.0,20),
            new Pokemon("Lilligant","Grass",-100.0,20),
            new Pokemon("Shroomish","Fairy","Grass",50.0,15),
            new Pokemon("Breloom","Fairy","Grass",50.0,15),
            new Pokemon("Applin","Grass","Dragon",50.0,20),
            new Pokemon("Flapple","Grass","Dragon",50.0,20),
            new Pokemon("Appletun","Grass","Dragon",50.0,20),
            new Pokemon("Spoink","Field",50.0,20),
            new Pokemon("Grumpig","Field",50.0,20),
            new Pokemon("Squawkabilly","Flying",50.0,15),
            new Pokemon("Misdreavus","Amorphous",50.0,25),
            new Pokemon("Mismagius","Amorphous",50.0,25),
            new Pokemon("Makuhita","Human-Like",75.0,20),
            new Pokemon("Hariyama","Human-Like",75.0,20),
            new Pokemon("Crabrawler","Water 3",50.0,20),
            new Pokemon("Crabominable","Water 3",50.0,20),
            new Pokemon("Salandit","Monster","Dragon",87.5,20),
            new Pokemon("Salazzle","Monster","Dragon",-100.0,20),
            new Pokemon("Phanpy","Field",50.0,20),
            new Pokemon("Donphan","Field",50.0,20),
            new Pokemon("Cufant","Field","Mineral",50.0,25),
            new Pokemon("Copperajah","Field","Mineral",50.0,25),
            new Pokemon("Gible","Monster","Dragon",50.0,40),
            new Pokemon("Gabite","Monster","Dragon",50.0,40),
            new Pokemon("Garchomp","Monster","Dragon",50.0,40),
            new Pokemon("Nacli","Mineral",50.0,20),
            new Pokemon("Naclstack","Mineral",50.0,20),
            new Pokemon("Garganacl","Mineral",50.0,20),
            new Pokemon("Wingull","Water 1","Flying",50.0,20),
            new Pokemon("Pelipper","Water 1","Flying",50.0,20),
            new Pokemon("Magikarp","Water 2","Dragon",50.0,5),
            new Pokemon("Gyarados","Water 2","Dragon",50.0,5),
            new Pokemon("Arrokuda","Water 2",50.0,20),
            new Pokemon("Barraskewda","Water 2",50.0,20),
            new Pokemon("Basculin","Water 2",50.0,40),
            new Pokemon("Gulpin","Amorphous",50.0,20),
            new Pokemon("Swalot","Amorphous",50.0,20),
            new Pokemon("Meowth","Field",50.0,20),
            new Pokemon("Persian","Field",50.0,20),
            new Pokemon("Drifloon","Amorphous",50.0,30),
            new Pokemon("Drifblim","Amorphous",50.0,30),
            new Pokemon("Flabebe","Fairy",-100.0,20),
            new Pokemon("Floette","Fairy",-100.0,20),
            new Pokemon("Florges","Fairy",-100.0,20),
            new Pokemon("Diglett","Field",50.0,20),
            new Pokemon("Dugtrio","Field",50.0,20),
            new Pokemon("Torkoal","Field",50.0,20),
            new Pokemon("Numel","Field",50.0,20),
            new Pokemon("Camerupt","Field",50.0,20),
            new Pokemon("Bronzor","Mineral",0,20),
            new Pokemon("Bronzong","Mineral",0,20),
            new Pokemon("Axew","Monster","Dragon",50.0,40),
            new Pokemon("Fraxure","Monster","Dragon",50.0,40),
            new Pokemon("Haxorus","Monster","Dragon",50.0,40),
            new Pokemon("Mankey","Field",50.0,20),
            new Pokemon("Primeape","Field",50.0,20),
            new Pokemon("Annihilape","Field",50.0,20),
            new Pokemon("Meditite","Human-Like",50.0,20),
            new Pokemon("Medicham","Human-Like",50.0,20),
            new Pokemon("Riolu","Undiscovered",87.5,25),
            new Pokemon("Lucario","Field","Human-Like",87.5,25),
            new Pokemon("Charcadet","Human-Like",50.0,35),
            new Pokemon("Armarouge","Human-Like",50.0,35),
            new Pokemon("Ceruledge","Human-Like",50.0,35),
            new Pokemon("Barboach","Water 2",50.0,20),
            new Pokemon("Whiscash","Water 2",50.0,20),
            new Pokemon("Tadbulb","Water 1",50.0,20),
            new Pokemon("Bellibolt","Water 1",50.0,20),
            new Pokemon("Goomy","Dragon",50.0,40),
            new Pokemon("Sliggoo","Dragon",50.0,40),
            new Pokemon("Goodra","Dragon",50.0,40),
            new Pokemon("Croagunk","Human-Like",50.0,10),
            new Pokemon("Toxicroak","Human-Like",50.0,20),
            new Pokemon("Wattrel","Water 1","Flying",50.0,20),
            new Pokemon("Kilowattrel","Water 1","Flying",50.0,20),
            new Pokemon("Eevee","Field",87.5,35),
            new Pokemon("Vaporeon","Field",87.5,35),
            new Pokemon("Jolteon","Field",87.5,35),
            new Pokemon("Flareon","Field",87.5,35),
            new Pokemon("Espeon","Field",87.5,35),
            new Pokemon("Umbreon","Field",87.5,35),
            new Pokemon("Leafeon","Field",87.5,35),
            new Pokemon("Glaceon","Field",87.5,35),
            new Pokemon("Sylveon","Field",87.5,35),
            new Pokemon("Dunsparce","Field",50.0,20),
            new Pokemon("Dudunsparce","Field",50.0,20),
            new Pokemon("Deerling","Field",50.0,20),
            new Pokemon("Sawsbuck","Field",50.0,20),
            new Pokemon("Girafarig","Field",50.0,20),
            new Pokemon("Farigiraf","Field",50.0,20),
            new Pokemon("Grimer","Amorphous",50.0,20),
            new Pokemon("Muk","Amorphous",50.0,20),
            new Pokemon("Maschiff","Field",50.0,20),
            new Pokemon("Mabosstiff","Field",50.0,20),
            new Pokemon("Toxel","Undiscovered",50.0,25),
            new Pokemon("Toxtricity","Human-Like",50.0,25),
            new Pokemon("Dedenne","Field","Fairy",50.0,20),
            new Pokemon("Pachirisu","Field","Fairy",50.0,10),
            new Pokemon("Shroodle","Field",50.0,20),
            new Pokemon("Grafaiai","Field",50.0,20),
            new Pokemon("Stantler","Field",50.0,20),
            new Pokemon("Foongus","Grass",50.0,20),
            new Pokemon("Amoonguss","Grass",50.0,20),
            new Pokemon("Voltorb","Mineral",0,20),
            new Pokemon("Electrode","Mineral",0,20),
            new Pokemon("Magnemite","Mineral",0,20),
            new Pokemon("Magneton","Mineral",0,20),
            new Pokemon("Magnezone","Mineral",0,20),
            new Pokemon("Ditto","Ditto",0,20),
            new Pokemon("Growlithe","Field",75.0,20),
            new Pokemon("Arcanine","Field",75.0,20),
            new Pokemon("Teddiursa","Field",50.0,20),
            new Pokemon("Ursaring","Field",50.0,20),
            new Pokemon("Zangoose","Field",50.0,20),
            new Pokemon("Seviper","Field","Dragon",50.0,20),
            new Pokemon("Swablu","Flying","Dragon",50.0,20),
            new Pokemon("Altaria","Flying","Dragon",50.0,20),
            new Pokemon("Skiddo","Field",50.0,20),
            new Pokemon("Gogoat","Field",50.0,20),
            new Pokemon("Tauros","Field",100.0,20),
            new Pokemon("Litleo","Field",12.5,20),
            new Pokemon("Pyroar","Field",12.5,20),
            new Pokemon("Stunky","Field",50.0,20),
            new Pokemon("Skuntank","Field",50.0,20),
            new Pokemon("Zorua","Field",87.5,25),
            new Pokemon("Zoroark","Field",87.5,20),
            new Pokemon("Sneasel","Field",50.0,20),
            new Pokemon("Weavile","Field",50.0,20),
            new Pokemon("Murkrow","Flying",50.0,20),
            new Pokemon("Honchkrow","Flying",50.0,20),
            new Pokemon("Gothita","Human-Like",25.0,20),
            new Pokemon("Gothorita","Human-Like",25.0,20),
            new Pokemon("Gothitelle","Human-Like",25.0,20),
            new Pokemon("Sinistea","Mineral","Amorphous",0,20),
            new Pokemon("Polteageist","Mineral","Amorphous",0,20),
            new Pokemon("Mimikyu","Amorphous",50.0,20),
            new Pokemon("Klefki","Mineral",50.0,20),
            new Pokemon("Indeedee","Fairy",50.0,40),
            new Pokemon("Bramblin","Grass",50.0,20),
            new Pokemon("Brambleghast","Grass",50.0,20),
            new Pokemon("Toedscool","Grass",50.0,20),
            new Pokemon("Toedscruel","Grass",50.0,20),
            new Pokemon("Tropius","Monster","Grass",50.0,25),
            new Pokemon("Fomantis","Grass",50.0,20),
            new Pokemon("Lurantis","Grass",50.0,20),
            new Pokemon("Klawf","Water 3",50.0,35),
            new Pokemon("Capsakid","Grass",50.0,20),
            new Pokemon("Scovillain","Grass",50.0,20),
            new Pokemon("Cacnea","Grass","Human-Like",50.0,20),
            new Pokemon("Cacturne","Grass","Human-Like",50.0,20),
            new Pokemon("Rellor","Bug",50.0,20),
            new Pokemon("Rabsca","Bug",50.0,20),
            new Pokemon("Venonat","Bug",50.0,20),
            new Pokemon("Venomoth","Bug",50.0,20),
            new Pokemon("Pineco","Bug",50.0,20),
            new Pokemon("Forretress","Bug",50.0,20),
            new Pokemon("Scyther","Bug",50.0,25),
            new Pokemon("Scizor","Bug",50.0,25),
            new Pokemon("Heracross","Bug",50.0,25),
            new Pokemon("Flittle","Flying",50.0,20),
            new Pokemon("Espathra","Flying",50.0,20),
            new Pokemon("Hippopotas","Field",50.0,30),
            new Pokemon("Hippowdon","Field",50.0,30),
            new Pokemon("Sandile","Field",50.0,20),
            new Pokemon("Krokorok","Field",50.0,20),
            new Pokemon("Krookodile","Field",50.0,20),
            new Pokemon("Silicobra","Field","Dragon",50.0,20),
            new Pokemon("Sandaconda","Field","Dragon",50.0,20),
            new Pokemon("Mudbray","Field",50.0,20),
            new Pokemon("Mudsdale","Field",50.0,20),
            new Pokemon("Larvesta","Bug",50.0,40),
            new Pokemon("Volcarona","Bug",50.0,40),
            new Pokemon("Bagon","Dragon",50.0,40),
            new Pokemon("Shelgon","Dragon",50.0,40),
            new Pokemon("Salamence","Dragon",50.0,40),
            new Pokemon("Tinkatink","Fairy",-100.0,20),
            new Pokemon("Tinkatuff","Fairy",-100.0,20),
            new Pokemon("Tinkaton","Fairy",-100.0,20),
            new Pokemon("Hatenna","Fairy",-100.0,20),
            new Pokemon("Hattrem","Fairy",-100.0,20),
            new Pokemon("Hatterene","Fairy",-100.0,20),
            new Pokemon("Impidimp","Fairy","Human-Like",100.0,20),
            new Pokemon("Morgrem","Fairy","Human-Like",100.0,20),
            new Pokemon("Grimmsnarl","Fairy","Human-Like",100.0,20),
            new Pokemon("Wiglett","Water 3",50.0,20),
            new Pokemon("Wugtrio","Water 3",50.0,20),
            new Pokemon("Bombirdier","Flying",50.0,35),
            new Pokemon("Finizen","Field","Water 2",50.0,40),
            new Pokemon("Palafin","Field","Water 2",50.0,40),
            new Pokemon("Varoom","Mineral",50.0,20),
            new Pokemon("Revavroom","Mineral",50.0,20),
            new Pokemon("Cyclizar","Field",50.0,30),
            new Pokemon("Orthworm","Field",50.0,35),
            new Pokemon("Sableye","Human-Like",50.0,25),
            new Pokemon("Shuppet","Amorphous",50.0,25),
            new Pokemon("Banette","Amorphous",50.0,25),
            new Pokemon("Falinks","Fairy","Mineral",0,25),
            new Pokemon("Hawlucha","Flying","Human-Like",50.0,20),
            new Pokemon("Spiritomb","Amorphous",50.0,30),
            new Pokemon("Noibat","Flying","Dragon",50.0,20),
            new Pokemon("Noivern","Flying","Dragon",50.0,20),
            new Pokemon("Dreepy","Amorphous","Dragon",50.0,40),
            new Pokemon("Drakloak","Amorphous","Dragon",50.0,40),
            new Pokemon("Dragapult","Amorphous","Dragon",50.0,40),
            new Pokemon("Glimmet","Mineral",50.0,30),
            new Pokemon("Glimmora","Mineral",50.0,30),
            new Pokemon("Rotom","Amorphous",0,20),
            new Pokemon("Greavard","Field",50.0,20),
            new Pokemon("Houndstone","Field",50.0,20),
            new Pokemon("Oranguru","Field",50.0,20),
            new Pokemon("Passimian","Field",50.0,20),
            new Pokemon("Komala","Field",50.0,20),
            new Pokemon("Larvitar","Monster",50.0,40),
            new Pokemon("Pupitar","Monster",50.0,40),
            new Pokemon("Tyranitar","Monster",50.0,40),
            new Pokemon("Stonjourner","Mineral",50.0,25),
            new Pokemon("Eiscue","Water 1","Field",50.0,25),
            new Pokemon("Pincurchin","Water 1","Amorphous",50.0,20),
            new Pokemon("Sandygast","Amorphous",50.0,15),
            new Pokemon("Palossand","Amorphous",50.0,15),
            new Pokemon("Slowpoke","Monster","Water 1",50.0,20),
            new Pokemon("Slowbro","Monster","Water 1",50.0,20),
            new Pokemon("Slowking","Monster","Water 1",50.0,20),
            new Pokemon("Shellos","Water 1","Amorphous",50.0,20),
            new Pokemon("Gastrodon","Water 1","Amorphous",50.0,20),
            new Pokemon("Shellder","Water 3",50.0,20),
            new Pokemon("Cloyster","Water 3",50.0,20),
            new Pokemon("Qwilfish","Water 2",50.0,20),
            new Pokemon("Luvdisc","Water 2",25.0,20),
            new Pokemon("Finneon","Water 2",50.0,20),
            new Pokemon("Lumineon","Water 2",50.0,20),
            new Pokemon("Bruxish","Water 2",50.0,15),
            new Pokemon("Alomomola","Water 1","Water 2",50.0,40),
            new Pokemon("Skrelp","Water 1","Dragon",50.0,20),
            new Pokemon("Dragalge","Water 1","Dragon",50.0,20),
            new Pokemon("Clauncher","Water 1","Water 3",50.0,15),
            new Pokemon("Clawitzer","Water 1","Water 3",50.0,15),
            new Pokemon("Tynamo","Amorphous",50.0,20),
            new Pokemon("Eelektrik","Amorphous",50.0,20),
            new Pokemon("Eelektross","Amorphous",50.0,20),
            new Pokemon("Mareanie","Water 1",50.0,20),
            new Pokemon("Toxapex","Water 1",50.0,20),
            new Pokemon("Flamigo","Flying",50.0,20),
            new Pokemon("Dratini","Water 1","Dragon",50.0,40),
            new Pokemon("Dragonair","Water 1","Dragon",50.0,40),
            new Pokemon("Dragonite","Water 1","Dragon",50.0,40),
            new Pokemon("Snom","Bug",50.0,20),
            new Pokemon("Frosmoth","Bug",50.0,20),
            new Pokemon("Snover","Monster","Grass",50.0,20),
            new Pokemon("Abomasnow","Monster","Grass",50.0,20),
            new Pokemon("Delibird","Water 1","Field",50.0,20),
            new Pokemon("Cubchoo","Field",50.0,20),
            new Pokemon("Beartic","Field",50.0,20),
            new Pokemon("Snorunt","Fairy","Mineral",50.0,20),
            new Pokemon("Glalie","Fairy","Mineral",50.0,20),
            new Pokemon("Froslass","Fairy","Mineral",-100.0,20),
            new Pokemon("Cryogonal","Mineral",0,25),
            new Pokemon("Cetoddle","Field",50.0,25),
            new Pokemon("Cetitan","Field",50.0,25),
            new Pokemon("Bergmite","Monster","Mineral",50.0,20),
            new Pokemon("Avalugg","Monster","Mineral",50.0,20),
            new Pokemon("Rufflet","Flying",100.0,20),
            new Pokemon("Braviary","Flying",100.0,20),
            new Pokemon("Pawniard","Human-Like",50.0,20),
            new Pokemon("Bisharp","Human-Like",50.0,20),
            new Pokemon("Kingambit","Human-Like",50.0,20),
            new Pokemon("Deino","Dragon",50.0,40),
            new Pokemon("Zweilous","Dragon",50.0,40),
            new Pokemon("Hydreigon","Dragon",50.0,40),
            new Pokemon("Veluza","Water 2",50.0,20),
            new Pokemon("Dondozo","Water 2",50.0,40),
            new Pokemon("Tatsugiri","Water 2",50.0,35),
            new Pokemon("Great-tusk","Undiscovered",0.0,50),
            new Pokemon("Scream-tail","Undiscovered",0.0,50),
            new Pokemon("Brute-bonnet","Undiscovered",0.0,50),
            new Pokemon("Flutter-mane","Undiscovered",0.0,50),
            new Pokemon("Slither-wing","Undiscovered",0.0,50),
            new Pokemon("Sandy-shocks","Undiscovered",0.0,50),
            new Pokemon("Iron-treads","Undiscovered",0.0,50),
            new Pokemon("Iron-bundle","Undiscovered",0.0,50),
            new Pokemon("Iron-hands","Undiscovered",0.0,50),
            new Pokemon("Iron-jugulis","Undiscovered",0.0,50),
            new Pokemon("Iron-moth","Undiscovered",0.0,50),
            new Pokemon("Iron-thorns","Undiscovered",0.0,50),
            new Pokemon("Frigibax","Dragon","Mineral",50.0,40),
            new Pokemon("Arctibax","Dragon","Mineral",50.0,40),
            new Pokemon("Baxcalibur","Dragon","Mineral",50.0,40),
            new Pokemon("Gimmighoul","Undiscovered",0.0,50),
            new Pokemon("Gholdengo","Undiscovered",0.0,50),
            new Pokemon("Wo-chien","Undiscovered",0.0,50),
            new Pokemon("Chien-pao","Undiscovered",0.0,50),
            new Pokemon("Ting-lu","Undiscovered",0.0,50),
            new Pokemon("Chi-yu","Undiscovered",0.0,50),
            new Pokemon("Roaring-moon","Undiscovered",0.0,50),
            new Pokemon("Iron-valiant","Undiscovered",0.0,50),
            new Pokemon("Koraidon","Undiscovered",0.0,50),
            new Pokemon("Miraidon","Undiscovered",0.0,50),
    };

    //svdex+dlc+hometransferrables
    private static final Pokemon[] SVDLCdex = {
            //Paldean Dex
            new Pokemon("Floragato","Field","Grass",87.5,20),
            new Pokemon("Meowscarada","Field","Grass",87.5,20),
            new Pokemon("Fuecoco","Field",87.5,20),
            new Pokemon("Crocalor","Field",87.5,20),
            new Pokemon("Skeledirge","Field",87.5,20),
            new Pokemon("Quaxly","Flying","Water 1",87.5,20),
            new Pokemon("Quaxwell","Flying","Water 1",87.5,20),
            new Pokemon("Quaquaval","Flying","Water 1",87.5,20),
            new Pokemon("Lechonk","Field",50.0,15),
            new Pokemon("Oinkologne","Field",100.0,15),
            new Pokemon("Tarountula","Bug",50.0,15),
            new Pokemon("Spidops","Bug",50.0,15),
            new Pokemon("Nymble","Bug",50.0,20),
            new Pokemon("Lokix","Bug",50.0,20),
            new Pokemon("Hoppip","Fairy","Grass",50.0,20),
            new Pokemon("Skiploom","Fairy","Grass",50.0,20),
            new Pokemon("Jumpluff","Fairy","Grass",50.0,20),
            new Pokemon("Fletchling","Flying",50.0,15),
            new Pokemon("Fletchinder","Flying",50.0,15),
            new Pokemon("Talonflame","Flying",50.0,15),
            new Pokemon("Pawmi","Field",50.0,15),
            new Pokemon("Pawmo","Field",50.0,15),
            new Pokemon("Pawmot","Field",50.0,15),
            new Pokemon("Houndour","Field",50.0,20),
            new Pokemon("Houndoom","Field",50.0,20),
            new Pokemon("Yungoos","Field",50.0,15),
            new Pokemon("Gumshoos","Field",50.0,15),
            new Pokemon("Skwovet","Field",50.0,20),
            new Pokemon("Greedent","Field",50.0,20),
            new Pokemon("Sunkern","Grass",50.0,20),
            new Pokemon("Sunflora","Grass",50.0,20),
            new Pokemon("Kricketot","Bug",50.0,15),
            new Pokemon("Kricketune","Bug",50.0,15),
            new Pokemon("Scatterbug","Bug",50.0,15),
            new Pokemon("Spewpa","Bug",50.0,15),
            new Pokemon("Vivillon","Bug",50.0,15),
            new Pokemon("Combee","Bug",87.5,15),
            new Pokemon("Vespiquen","Bug",-100.0,15),
            new Pokemon("Rookidee","Flying",50.0,15),
            new Pokemon("Corvisquire","Flying",50.0,15),
            new Pokemon("Corviknight","Flying",50.0,15),
            new Pokemon("Happiny","Undiscovered",-100.0,40),
            new Pokemon("Chansey","Fairy",-100.0,40),
            new Pokemon("Blissey","Fairy",-100.0,40),
            new Pokemon("Azurill","Undiscovered",25.0,10),
            new Pokemon("Marill","Water 1","Fairy",50.0,10),
            new Pokemon("Azumarill","Water 1","Fairy",50.0,10),
            new Pokemon("Surskit","Water 1","Bug",50.0,15),
            new Pokemon("Masquerain","Water 1","Bug",50.0,15),
            new Pokemon("Buizel","Water 1","Field",50.0,20),
            new Pokemon("Floatzel","Water 1","Field",50.0,20),
            new Pokemon("Wooper","Water 1","Field",50.0,20),
            new Pokemon("Clodsire","Water 1","Field",50.0,20),
            new Pokemon("Psyduck","Water 1","Field",50.0,20),
            new Pokemon("Golduck","Water 1","Field",50.0,20),
            new Pokemon("Chewtle","Monster","Water 1",50.0,20),
            new Pokemon("Drednaw","Monster","Water 1",50.0,20),
            new Pokemon("Igglybuff","Undiscovered",25.0,10),
            new Pokemon("Jigglypuff","Fairy",25.0,10),
            new Pokemon("Wigglytuff","Fairy",25.0,10),
            new Pokemon("Ralts","Human-Like","Amorphous",50.0,20),
            new Pokemon("Kirlia","Human-Like","Amorphous",50.0,20),
            new Pokemon("Gardevoir","Human-Like","Amorphous",50.0,20),
            new Pokemon("Gallade","Human-Like","Amorphous",100.0,20),
            new Pokemon("Drowzee","Human-Like",50.0,20),
            new Pokemon("Hypno","Human-Like",50.0,20),
            new Pokemon("Gastly","Amorphous",50.0,20),
            new Pokemon("Haunter","Amorphous",50.0,20),
            new Pokemon("Gengar","Amorphous",50.0,20),
            new Pokemon("Tandemaus","Field","Fairy",0,10),
            new Pokemon("Maushold","Field","Fairy",0,10),
            new Pokemon("Pichu","Undiscovered",50.0,10),
            new Pokemon("Pikachu","Field","Fairy",50.0,10),
            new Pokemon("Raichu","Field","Fairy",50.0,10),
            new Pokemon("Fidough","Field","Mineral",50.0,20),
            new Pokemon("Dachsbun","Field","Mineral",50.0,20),
            new Pokemon("Slakoth","Field",50.0,15),
            new Pokemon("Vigoroth","Field",50.0,15),
            new Pokemon("Slaking","Field",50.0,15),
            new Pokemon("Bounsweet","Grass",-100.0,20),
            new Pokemon("Steenee","Grass",-100.0,20),
            new Pokemon("Tsareena","Grass",-100.0,20),
            new Pokemon("Smoliv","Grass",50.0,20),
            new Pokemon("Dolliv","Grass",50.0,20),
            new Pokemon("Arboliva","Grass",50.0,20),
            new Pokemon("Bonsly","Undiscovered",50.0,20),
            new Pokemon("Sudowoodo","Mineral",50.0,20),
            new Pokemon("Rockruff","Field",50.0,15),
            new Pokemon("Lycanroc","Field",50.0,15),
            new Pokemon("Rolycoly","Mineral",50.0,15),
            new Pokemon("Carkol","Mineral",50.0,15),
            new Pokemon("Coalossal","Mineral",50.0,15),
            new Pokemon("Shinx","Field",50.0,20),
            new Pokemon("Luxio","Field",50.0,20),
            new Pokemon("Luxray","Field",50.0,20),
            new Pokemon("Starly","Flying",50.0,15),
            new Pokemon("Staravia","Flying",50.0,15),
            new Pokemon("Staraptor","Flying",50.0,15),
            new Pokemon("Oricorio","Flying",25.0,20),
            new Pokemon("Mareep","Monster","Field",50.0,20),
            new Pokemon("Flaaffy","Monster","Field",50.0,20),
            new Pokemon("Ampharos","Monster","Field",50.0,20),
            new Pokemon("Petilil","Grass",-100.0,20),
            new Pokemon("Lilligant","Grass",-100.0,20),
            new Pokemon("Shroomish","Fairy","Grass",50.0,15),
            new Pokemon("Breloom","Fairy","Grass",50.0,15),
            new Pokemon("Applin","Grass","Dragon",50.0,20),
            new Pokemon("Flapple","Grass","Dragon",50.0,20),
            new Pokemon("Appletun","Grass","Dragon",50.0,20),
            new Pokemon("Spoink","Field",50.0,20),
            new Pokemon("Grumpig","Field",50.0,20),
            new Pokemon("Squawkabilly","Flying",50.0,15),
            new Pokemon("Misdreavus","Amorphous",50.0,25),
            new Pokemon("Mismagius","Amorphous",50.0,25),
            new Pokemon("Makuhita","Human-Like",75.0,20),
            new Pokemon("Hariyama","Human-Like",75.0,20),
            new Pokemon("Crabrawler","Water 3",50.0,20),
            new Pokemon("Crabominable","Water 3",50.0,20),
            new Pokemon("Salandit","Monster","Dragon",87.5,20),
            new Pokemon("Salazzle","Monster","Dragon",-100.0,20),
            new Pokemon("Phanpy","Field",50.0,20),
            new Pokemon("Donphan","Field",50.0,20),
            new Pokemon("Cufant","Field","Mineral",50.0,25),
            new Pokemon("Copperajah","Field","Mineral",50.0,25),
            new Pokemon("Gible","Monster","Dragon",50.0,40),
            new Pokemon("Gabite","Monster","Dragon",50.0,40),
            new Pokemon("Garchomp","Monster","Dragon",50.0,40),
            new Pokemon("Nacli","Mineral",50.0,20),
            new Pokemon("Naclstack","Mineral",50.0,20),
            new Pokemon("Garganacl","Mineral",50.0,20),
            new Pokemon("Wingull","Water 1","Flying",50.0,20),
            new Pokemon("Pelipper","Water 1","Flying",50.0,20),
            new Pokemon("Magikarp","Water 2","Dragon",50.0,5),
            new Pokemon("Gyarados","Water 2","Dragon",50.0,5),
            new Pokemon("Arrokuda","Water 2",50.0,20),
            new Pokemon("Barraskewda","Water 2",50.0,20),
            new Pokemon("Basculin","Water 2",50.0,40),
            new Pokemon("Gulpin","Amorphous",50.0,20),
            new Pokemon("Swalot","Amorphous",50.0,20),
            new Pokemon("Meowth","Field",50.0,20),
            new Pokemon("Persian","Field",50.0,20),
            new Pokemon("Drifloon","Amorphous",50.0,30),
            new Pokemon("Drifblim","Amorphous",50.0,30),
            new Pokemon("Flabebe","Fairy",-100.0,20),
            new Pokemon("Floette","Fairy",-100.0,20),
            new Pokemon("Florges","Fairy",-100.0,20),
            new Pokemon("Diglett","Field",50.0,20),
            new Pokemon("Dugtrio","Field",50.0,20),
            new Pokemon("Torkoal","Field",50.0,20),
            new Pokemon("Numel","Field",50.0,20),
            new Pokemon("Camerupt","Field",50.0,20),
            new Pokemon("Bronzor","Mineral",0,20),
            new Pokemon("Bronzong","Mineral",0,20),
            new Pokemon("Axew","Monster","Dragon",50.0,40),
            new Pokemon("Fraxure","Monster","Dragon",50.0,40),
            new Pokemon("Haxorus","Monster","Dragon",50.0,40),
            new Pokemon("Mankey","Field",50.0,20),
            new Pokemon("Primeape","Field",50.0,20),
            new Pokemon("Annihilape","Field",50.0,20),
            new Pokemon("Meditite","Human-Like",50.0,20),
            new Pokemon("Medicham","Human-Like",50.0,20),
            new Pokemon("Riolu","Undiscovered",87.5,25),
            new Pokemon("Lucario","Field","Human-Like",87.5,25),
            new Pokemon("Charcadet","Human-Like",50.0,35),
            new Pokemon("Armarouge","Human-Like",50.0,35),
            new Pokemon("Ceruledge","Human-Like",50.0,35),
            new Pokemon("Barboach","Water 2",50.0,20),
            new Pokemon("Whiscash","Water 2",50.0,20),
            new Pokemon("Tadbulb","Water 1",50.0,20),
            new Pokemon("Bellibolt","Water 1",50.0,20),
            new Pokemon("Goomy","Dragon",50.0,40),
            new Pokemon("Sliggoo","Dragon",50.0,40),
            new Pokemon("Goodra","Dragon",50.0,40),
            new Pokemon("Croagunk","Human-Like",50.0,10),
            new Pokemon("Toxicroak","Human-Like",50.0,20),
            new Pokemon("Wattrel","Water 1","Flying",50.0,20),
            new Pokemon("Kilowattrel","Water 1","Flying",50.0,20),
            new Pokemon("Eevee","Field",87.5,35),
            new Pokemon("Vaporeon","Field",87.5,35),
            new Pokemon("Jolteon","Field",87.5,35),
            new Pokemon("Flareon","Field",87.5,35),
            new Pokemon("Espeon","Field",87.5,35),
            new Pokemon("Umbreon","Field",87.5,35),
            new Pokemon("Leafeon","Field",87.5,35),
            new Pokemon("Glaceon","Field",87.5,35),
            new Pokemon("Sylveon","Field",87.5,35),
            new Pokemon("Dunsparce","Field",50.0,20),
            new Pokemon("Dudunsparce","Field",50.0,20),
            new Pokemon("Deerling","Field",50.0,20),
            new Pokemon("Sawsbuck","Field",50.0,20),
            new Pokemon("Girafarig","Field",50.0,20),
            new Pokemon("Farigiraf","Field",50.0,20),
            new Pokemon("Grimer","Amorphous",50.0,20),
            new Pokemon("Muk","Amorphous",50.0,20),
            new Pokemon("Maschiff","Field",50.0,20),
            new Pokemon("Mabosstiff","Field",50.0,20),
            new Pokemon("Toxel","Undiscovered",50.0,25),
            new Pokemon("Toxtricity","Human-Like",50.0,25),
            new Pokemon("Dedenne","Field","Fairy",50.0,20),
            new Pokemon("Pachirisu","Field","Fairy",50.0,10),
            new Pokemon("Shroodle","Field",50.0,20),
            new Pokemon("Grafaiai","Field",50.0,20),
            new Pokemon("Stantler","Field",50.0,20),
            new Pokemon("Foongus","Grass",50.0,20),
            new Pokemon("Amoonguss","Grass",50.0,20),
            new Pokemon("Voltorb","Mineral",0,20),
            new Pokemon("Electrode","Mineral",0,20),
            new Pokemon("Magnemite","Mineral",0,20),
            new Pokemon("Magneton","Mineral",0,20),
            new Pokemon("Magnezone","Mineral",0,20),
            new Pokemon("Ditto","Ditto",0,20),
            new Pokemon("Growlithe","Field",75.0,20),
            new Pokemon("Arcanine","Field",75.0,20),
            new Pokemon("Teddiursa","Field",50.0,20),
            new Pokemon("Ursaring","Field",50.0,20),
            new Pokemon("Zangoose","Field",50.0,20),
            new Pokemon("Seviper","Field","Dragon",50.0,20),
            new Pokemon("Swablu","Flying","Dragon",50.0,20),
            new Pokemon("Altaria","Flying","Dragon",50.0,20),
            new Pokemon("Skiddo","Field",50.0,20),
            new Pokemon("Gogoat","Field",50.0,20),
            new Pokemon("Tauros","Field",100.0,20),
            new Pokemon("Litleo","Field",12.5,20),
            new Pokemon("Pyroar","Field",12.5,20),
            new Pokemon("Stunky","Field",50.0,20),
            new Pokemon("Skuntank","Field",50.0,20),
            new Pokemon("Zorua","Field",87.5,25),
            new Pokemon("Zoroark","Field",87.5,20),
            new Pokemon("Sneasel","Field",50.0,20),
            new Pokemon("Weavile","Field",50.0,20),
            new Pokemon("Murkrow","Flying",50.0,20),
            new Pokemon("Honchkrow","Flying",50.0,20),
            new Pokemon("Gothita","Human-Like",25.0,20),
            new Pokemon("Gothorita","Human-Like",25.0,20),
            new Pokemon("Gothitelle","Human-Like",25.0,20),
            new Pokemon("Sinistea","Mineral","Amorphous",0,20),
            new Pokemon("Polteageist","Mineral","Amorphous",0,20),
            new Pokemon("Mimikyu","Amorphous",50.0,20),
            new Pokemon("Klefki","Mineral",50.0,20),
            new Pokemon("Indeedee","Fairy",50.0,40),
            new Pokemon("Bramblin","Grass",50.0,20),
            new Pokemon("Brambleghast","Grass",50.0,20),
            new Pokemon("Toedscool","Grass",50.0,20),
            new Pokemon("Toedscruel","Grass",50.0,20),
            new Pokemon("Tropius","Monster","Grass",50.0,25),
            new Pokemon("Fomantis","Grass",50.0,20),
            new Pokemon("Lurantis","Grass",50.0,20),
            new Pokemon("Klawf","Water 3",50.0,35),
            new Pokemon("Capsakid","Grass",50.0,20),
            new Pokemon("Scovillain","Grass",50.0,20),
            new Pokemon("Cacnea","Grass","Human-Like",50.0,20),
            new Pokemon("Cacturne","Grass","Human-Like",50.0,20),
            new Pokemon("Rellor","Bug",50.0,20),
            new Pokemon("Rabsca","Bug",50.0,20),
            new Pokemon("Venonat","Bug",50.0,20),
            new Pokemon("Venomoth","Bug",50.0,20),
            new Pokemon("Pineco","Bug",50.0,20),
            new Pokemon("Forretress","Bug",50.0,20),
            new Pokemon("Scyther","Bug",50.0,25),
            new Pokemon("Scizor","Bug",50.0,25),
            new Pokemon("Heracross","Bug",50.0,25),
            new Pokemon("Flittle","Flying",50.0,20),
            new Pokemon("Espathra","Flying",50.0,20),
            new Pokemon("Hippopotas","Field",50.0,30),
            new Pokemon("Hippowdon","Field",50.0,30),
            new Pokemon("Sandile","Field",50.0,20),
            new Pokemon("Krokorok","Field",50.0,20),
            new Pokemon("Krookodile","Field",50.0,20),
            new Pokemon("Silicobra","Field","Dragon",50.0,20),
            new Pokemon("Sandaconda","Field","Dragon",50.0,20),
            new Pokemon("Mudbray","Field",50.0,20),
            new Pokemon("Mudsdale","Field",50.0,20),
            new Pokemon("Larvesta","Bug",50.0,40),
            new Pokemon("Volcarona","Bug",50.0,40),
            new Pokemon("Bagon","Dragon",50.0,40),
            new Pokemon("Shelgon","Dragon",50.0,40),
            new Pokemon("Salamence","Dragon",50.0,40),
            new Pokemon("Tinkatink","Fairy",-100.0,20),
            new Pokemon("Tinkatuff","Fairy",-100.0,20),
            new Pokemon("Tinkaton","Fairy",-100.0,20),
            new Pokemon("Hatenna","Fairy",-100.0,20),
            new Pokemon("Hattrem","Fairy",-100.0,20),
            new Pokemon("Hatterene","Fairy",-100.0,20),
            new Pokemon("Impidimp","Fairy","Human-Like",100.0,20),
            new Pokemon("Morgrem","Fairy","Human-Like",100.0,20),
            new Pokemon("Grimmsnarl","Fairy","Human-Like",100.0,20),
            new Pokemon("Wiglett","Water 3",50.0,20),
            new Pokemon("Wugtrio","Water 3",50.0,20),
            new Pokemon("Bombirdier","Flying",50.0,35),
            new Pokemon("Finizen","Field","Water 2",50.0,40),
            new Pokemon("Palafin","Field","Water 2",50.0,40),
            new Pokemon("Varoom","Mineral",50.0,20),
            new Pokemon("Revavroom","Mineral",50.0,20),
            new Pokemon("Cyclizar","Field",50.0,30),
            new Pokemon("Orthworm","Field",50.0,35),
            new Pokemon("Sableye","Human-Like",50.0,25),
            new Pokemon("Shuppet","Amorphous",50.0,25),
            new Pokemon("Banette","Amorphous",50.0,25),
            new Pokemon("Falinks","Fairy","Mineral",0,25),
            new Pokemon("Hawlucha","Flying","Human-Like",50.0,20),
            new Pokemon("Spiritomb","Amorphous",50.0,30),
            new Pokemon("Noibat","Flying","Dragon",50.0,20),
            new Pokemon("Noivern","Flying","Dragon",50.0,20),
            new Pokemon("Dreepy","Amorphous","Dragon",50.0,40),
            new Pokemon("Drakloak","Amorphous","Dragon",50.0,40),
            new Pokemon("Dragapult","Amorphous","Dragon",50.0,40),
            new Pokemon("Glimmet","Mineral",50.0,30),
            new Pokemon("Glimmora","Mineral",50.0,30),
            new Pokemon("Rotom","Amorphous",0,20),
            new Pokemon("Greavard","Field",50.0,20),
            new Pokemon("Houndstone","Field",50.0,20),
            new Pokemon("Oranguru","Field",50.0,20),
            new Pokemon("Passimian","Field",50.0,20),
            new Pokemon("Komala","Field",50.0,20),
            new Pokemon("Larvitar","Monster",50.0,40),
            new Pokemon("Pupitar","Monster",50.0,40),
            new Pokemon("Tyranitar","Monster",50.0,40),
            new Pokemon("Stonjourner","Mineral",50.0,25),
            new Pokemon("Eiscue","Water 1","Field",50.0,25),
            new Pokemon("Pincurchin","Water 1","Amorphous",50.0,20),
            new Pokemon("Sandygast","Amorphous",50.0,15),
            new Pokemon("Palossand","Amorphous",50.0,15),
            new Pokemon("Slowpoke","Monster","Water 1",50.0,20),
            new Pokemon("Slowbro","Monster","Water 1",50.0,20),
            new Pokemon("Slowking","Monster","Water 1",50.0,20),
            new Pokemon("Shellos","Water 1","Amorphous",50.0,20),
            new Pokemon("Gastrodon","Water 1","Amorphous",50.0,20),
            new Pokemon("Shellder","Water 3",50.0,20),
            new Pokemon("Cloyster","Water 3",50.0,20),
            new Pokemon("Qwilfish","Water 2",50.0,20),
            new Pokemon("Luvdisc","Water 2",25.0,20),
            new Pokemon("Finneon","Water 2",50.0,20),
            new Pokemon("Lumineon","Water 2",50.0,20),
            new Pokemon("Bruxish","Water 2",50.0,15),
            new Pokemon("Alomomola","Water 1","Water 2",50.0,40),
            new Pokemon("Skrelp","Water 1","Dragon",50.0,20),
            new Pokemon("Dragalge","Water 1","Dragon",50.0,20),
            new Pokemon("Clauncher","Water 1","Water 3",50.0,15),
            new Pokemon("Clawitzer","Water 1","Water 3",50.0,15),
            new Pokemon("Tynamo","Amorphous",50.0,20),
            new Pokemon("Eelektrik","Amorphous",50.0,20),
            new Pokemon("Eelektross","Amorphous",50.0,20),
            new Pokemon("Mareanie","Water 1",50.0,20),
            new Pokemon("Toxapex","Water 1",50.0,20),
            new Pokemon("Flamigo","Flying",50.0,20),
            new Pokemon("Dratini","Water 1","Dragon",50.0,40),
            new Pokemon("Dragonair","Water 1","Dragon",50.0,40),
            new Pokemon("Dragonite","Water 1","Dragon",50.0,40),
            new Pokemon("Snom","Bug",50.0,20),
            new Pokemon("Frosmoth","Bug",50.0,20),
            new Pokemon("Snover","Monster","Grass",50.0,20),
            new Pokemon("Abomasnow","Monster","Grass",50.0,20),
            new Pokemon("Delibird","Water 1","Field",50.0,20),
            new Pokemon("Cubchoo","Field",50.0,20),
            new Pokemon("Beartic","Field",50.0,20),
            new Pokemon("Snorunt","Fairy","Mineral",50.0,20),
            new Pokemon("Glalie","Fairy","Mineral",50.0,20),
            new Pokemon("Froslass","Fairy","Mineral",-100.0,20),
            new Pokemon("Cryogonal","Mineral",0,25),
            new Pokemon("Cetoddle","Field",50.0,25),
            new Pokemon("Cetitan","Field",50.0,25),
            new Pokemon("Bergmite","Monster","Mineral",50.0,20),
            new Pokemon("Avalugg","Monster","Mineral",50.0,20),
            new Pokemon("Rufflet","Flying",100.0,20),
            new Pokemon("Braviary","Flying",100.0,20),
            new Pokemon("Pawniard","Human-Like",50.0,20),
            new Pokemon("Bisharp","Human-Like",50.0,20),
            new Pokemon("Kingambit","Human-Like",50.0,20),
            new Pokemon("Deino","Dragon",50.0,40),
            new Pokemon("Zweilous","Dragon",50.0,40),
            new Pokemon("Hydreigon","Dragon",50.0,40),
            new Pokemon("Veluza","Water 2",50.0,20),
            new Pokemon("Dondozo","Water 2",50.0,40),
            new Pokemon("Tatsugiri","Water 2",50.0,35),
            new Pokemon("Great-tusk","Undiscovered",0.0,50),
            new Pokemon("Scream-tail","Undiscovered",0.0,50),
            new Pokemon("Brute-bonnet","Undiscovered",0.0,50),
            new Pokemon("Flutter-mane","Undiscovered",0.0,50),
            new Pokemon("Slither-wing","Undiscovered",0.0,50),
            new Pokemon("Sandy-shocks","Undiscovered",0.0,50),
            new Pokemon("Iron-treads","Undiscovered",0.0,50),
            new Pokemon("Iron-bundle","Undiscovered",0.0,50),
            new Pokemon("Iron-hands","Undiscovered",0.0,50),
            new Pokemon("Iron-jugulis","Undiscovered",0.0,50),
            new Pokemon("Iron-moth","Undiscovered",0.0,50),
            new Pokemon("Iron-thorns","Undiscovered",0.0,50),
            new Pokemon("Frigibax","Dragon","Mineral",50.0,40),
            new Pokemon("Arctibax","Dragon","Mineral",50.0,40),
            new Pokemon("Baxcalibur","Dragon","Mineral",50.0,40),
            new Pokemon("Gimmighoul","Undiscovered",0.0,50),
            new Pokemon("Gholdengo","Undiscovered",0.0,50),
            new Pokemon("Wo-chien","Undiscovered",0.0,50),
            new Pokemon("Chien-pao","Undiscovered",0.0,50),
            new Pokemon("Ting-lu","Undiscovered",0.0,50),
            new Pokemon("Chi-yu","Undiscovered",0.0,50),
            new Pokemon("Roaring-moon","Undiscovered",0.0,50),
            new Pokemon("Iron-valiant","Undiscovered",0.0,50),
            new Pokemon("Koraidon","Undiscovered",0.0,50),
            new Pokemon("Miraidon","Undiscovered",0.0,50),


            //dlc+hometransferrables
            new Pokemon("Bulbasaur", "Monster", "Grass", 87.5, 20),
            new Pokemon("Ivysaur", "Monster", "Grass", 87.5, 20),
            new Pokemon("Venusaur", "Monster", "Grass", 87.5, 20),
            new Pokemon("Charmander", "Monster", "Dragon", 87.5, 20),
            new Pokemon("Charmeleon", "Monster", "Dragon", 87.5, 20),
            new Pokemon("Charizard", "Monster", "Dragon", 87.5, 20),
            new Pokemon("Squirtle", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Wartortle", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Blastoise", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Sandshrew", "Field", 50.0, 20),
            new Pokemon("Sandslash", "Field", 50.0, 20),
            new Pokemon("Vulpix", "Field", 25.0, 20),
            new Pokemon("Ninetales", "Field", 25.0, 20),
            new Pokemon("Oddish", "Grass", 50.0, 20),
            new Pokemon("Gloom", "Grass", 50.0, 20),
            new Pokemon("Vileplume", "Grass", 50.0, 20),
            new Pokemon("Diglett", "Field", 50.0, 20),
            new Pokemon("Dugtrio", "Field", 50.0, 20),
            new Pokemon("Tentacool", "Water 3", 50.0, 20),
            new Pokemon("Tentacruel", "Water 3", 50.0, 20),
            new Pokemon("Geodude", "Mineral", 50.0, 20),
            new Pokemon("Graveler", "Mineral", 50.0, 20),
            new Pokemon("Golem", "Mineral", 50.0, 20),
            new Pokemon("Slowpoke", "Monster", "Water 1", 50.0, 20),
            new Pokemon("Slowbro", "Monster", "Water 1", 50.0, 20),
            new Pokemon("Doduo", "Flying", 50.0, 20),
            new Pokemon("Dodrio", "Flying", 50.0, 20),
            new Pokemon("Seel", "Water 1", "Field", 50.0, 20),
            new Pokemon("Dewgong", "Water 1", "Field", 50.0, 20),
            new Pokemon("Grimer", "Amorphous", 50.0, 20),
            new Pokemon("Muk", "Amorphous", 50.0, 20),
            new Pokemon("Exeggcute", "Grass", 50.0, 20),
            new Pokemon("Exeggutor", "Grass", "Dragon", 50.0, 20),
            new Pokemon("Hitmonlee", "Human-Like", 100.0, 25),
            new Pokemon("Hitmonchan", "Human-Like", 100.0, 25),
            new Pokemon("Rhyhorn", "Monster", "Field",50.0, 20),
            new Pokemon("Rhydon", "Monster", "Field",50.0, 20),
            new Pokemon("Horsea", "Water 1", "Dragon", 50.0, 20),
            new Pokemon("Seadra", "Water 1", "Dragon", 50.0, 20),
            new Pokemon("Electabuzz", "Human-Like", 75.0, 25),
            new Pokemon("Magmar", "Human-Like", 75.0, 25),
            new Pokemon("Tauros", "Field", 100.0, 20),
            new Pokemon("Lapras", "Monster", "Water 1", 50.0, 40),
            new Pokemon("Porygon", "Mineral",0.0, 20),
            new Pokemon("Chikorita", "Monster", "Grass", 87.5, 20),
            new Pokemon("Bayleef", "Monster", "Grass", 87.5, 20),
            new Pokemon("Meganium", "Monster", "Grass", 87.5, 20),
            new Pokemon("Cyndaquil", "Field", 87.5, 20),
            new Pokemon("Quilava", "Field", 87.5, 20),
            new Pokemon("Typhlosion", "Field", 87.5, 20),
            new Pokemon("Totodile", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Croconaw", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Feraligatr", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Chinchou", "Water 2", 50.0, 20),
            new Pokemon("Lanturn", "Water 2", 50.0, 20),
            new Pokemon("Bellossom", "Grass",  50.0, 20),
            new Pokemon("Slowking", "Monster", "Water 1", 50.0, 20),
            new Pokemon("Snubbull", "Fairy", "Field", 25.0, 20),
            new Pokemon("Granbull", "Fairy", "Field", 25.0, 20),
            new Pokemon("Skarmory", "Flying", 50.0, 25),
            new Pokemon("Kingdra", "Water 1", "Dragon", 50.0, 20),
            new Pokemon("Porygon2", "Mineral",0.0, 20),
            new Pokemon("Smeargle", "Field", 50.0, 20),
            new Pokemon("Tyrogue", "No-Eggs-Found", 100.0, 25),
            new Pokemon("Hitmontop", "Human-Like", 100.0, 25),
            new Pokemon("Elekid", "No-Eggs-Found", 75.0, 25),
            new Pokemon("Magby", "No-Eggs-Found", 75.0, 25),
            new Pokemon("Treecko", "Monster", "Dragon", 87.5, 20),
            new Pokemon("Grovyle", "Monster", "Dragon", 87.5, 20),
            new Pokemon("Sceptile", "Monster", "Dragon", 87.5, 20),
            new Pokemon("Torchic", "Field", 87.5, 20),
            new Pokemon("Combusken", "Field", 87.5, 20),
            new Pokemon("Blaziken", "Field", 87.5, 20),
            new Pokemon("Mudkip", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Marshtomp", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Swampert", "Monster", "Water 1", 87.5, 20),
            new Pokemon("Plusle", "Fairy", 50.0, 20),
            new Pokemon("Minun", "Fairy", 50.0, 20),
            new Pokemon("Trapinch", "Bug", "Dragon", 50.0, 20),
            new Pokemon("Vibrava", "Bug", "Dragon", 50.0, 20),
            new Pokemon("Flygon", "Bug", "Dragon", 50.0, 20),
            new Pokemon("Beldum", "Mineral",0.0, 40),
            new Pokemon("Metang", "Mineral",0.0, 40),
            new Pokemon("Metagross", "Mineral",0.0, 40),
            new Pokemon("Turtwig", "Monster", "Grass", 87.5, 20),
            new Pokemon("Grotle", "Monster", "Grass", 87.5, 20),
            new Pokemon("Torterra", "Monster", "Grass", 87.5, 20),
            new Pokemon("Chimchar", "Field","Human-Like", 87.5, 20),
            new Pokemon("Monferno", "Field","Human-Like", 87.5, 20),
            new Pokemon("Infernape", "Field","Human-Like", 87.5, 20),
            new Pokemon("Piplup", "Field", "Water 1", 87.5, 20),
            new Pokemon("Prinplup", "Field", "Water 1", 87.5, 20),
            new Pokemon("Empoleon", "Field", "Water 1", 87.5, 20),
            new Pokemon("Shieldon", "Monster", 87.5, 30),
            new Pokemon("Bastiodon", "Monster", 87.5, 30),
            new Pokemon("Cranidos", "Monster", 87.5, 30),
            new Pokemon("Rampardos", "Monster", 87.5, 30),
            new Pokemon("Rhyperior", "Monster", "Field",50.0, 20),
            new Pokemon("Electivire", "Human-Like", 75.0, 25),
            new Pokemon("Magmortar", "Human-Like", 75.0, 25),
            new Pokemon("Porygon-Z", "Mineral",0.0, 20),
            new Pokemon("Snivy", "Field", "Grass", 87.5, 20),
            new Pokemon("Servine", "Field", "Grass", 87.5, 20),
            new Pokemon("Serperior", "Field", "Grass", 87.5, 20),
            new Pokemon("Tepig", "Field", 87.5, 20),
            new Pokemon("Pignite", "Field", 87.5, 20),
            new Pokemon("Emboar", "Field", 87.5, 20),
            new Pokemon("Oshawott", "Field", 87.5, 20),
            new Pokemon("Dewott", "Field", 87.5, 20),
            new Pokemon("Samurott", "Field", 87.5, 20),
            new Pokemon("Blitzle", "Field", 50.0, 20),
            new Pokemon("Zebstrika", "Field", 50.0, 20),
            new Pokemon("Drilbur", "Field", 50.0, 20),
            new Pokemon("Excadrill", "Field", 50.0, 20),
            new Pokemon("Cottonee", "Grass", "Fairy", 50.0, 20),
            new Pokemon("Whimsicott", "Grass", "Fairy", 50.0, 20),
            new Pokemon("Scraggy", "Field", "Dragon", 50.0, 15),
            new Pokemon("Scrafty", "Field", "Dragon", 50.0, 15),
            new Pokemon("Minccino", "Field", 25.0, 15),
            new Pokemon("Cinccino", "Field", 25.0, 15),
            new Pokemon("Solosis", "Amorphous", 50.0, 20),
            new Pokemon("Duosion", "Amorphous", 50.0, 20),
            new Pokemon("Reuniclus", "Amorphous", 50.0, 20),
            new Pokemon("Joltik", "Bug", 50.0, 20),
            new Pokemon("Galvantula", "Bug", 50.0, 20),
            new Pokemon("Golett", "Mineral", 0.0, 25),
            new Pokemon("Golurk", "Mineral", 0.0, 25),
            new Pokemon("Chespin", "Field", 87.5, 20),
            new Pokemon("Quilladin", "Field", 87.5, 20),
            new Pokemon("Chesnaught", "Field", 87.5, 20),
            new Pokemon("Fennekin", "Field", 87.5, 20),
            new Pokemon("Braixen", "Field", 87.5, 20),
            new Pokemon("Delphox", "Field", 87.5, 20),
            new Pokemon("Froakie", "Water 1", 87.5, 20),
            new Pokemon("Frogadier", "Water 1", 87.5, 20),
            new Pokemon("Greninja", "Water 1", 87.5, 20),
            new Pokemon("Espurr", "Field", 50.0, 20),
            new Pokemon("Meowstic", "Field", 50.0, 20),
            new Pokemon("Inkay", "Water 1", "Water 2", 50.0, 20),
            new Pokemon("Malamar", "Water 1", "Water 2", 50.0, 20),
            new Pokemon("Rowlet", "Flying", 87.5, 20),
            new Pokemon("Dartrix", "Flying", 87.5, 20),
            new Pokemon("Decidueye", "Flying", 87.5, 20),
            new Pokemon("Litten", "Field", 87.5, 20),
            new Pokemon("Torracat", "Field", 87.5, 20),
            new Pokemon("Incineroar", "Field", 87.5, 20),
            new Pokemon("Popplio", "Field", "Water 1",87.5, 20),
            new Pokemon("Brionne", "Field", "Water 1",87.5, 20),
            new Pokemon("Primarina", "Field", "Water 1",87.5, 20),
            new Pokemon("Pikipek", "Flying", 50.0, 15),
            new Pokemon("Trumbeak", "Flying", 50.0, 15),
            new Pokemon("Toucannon", "Flying", 50.0, 15),
            new Pokemon("Dewpider", "Water 1", "Bug", 50.0, 15),
            new Pokemon("Araquanid", "Water 1", "Bug", 50.0, 15),
            new Pokemon("Comfey", "Grass", 25.0, 20),
            new Pokemon("Minior", "Mineral",0.0, 25),
            new Pokemon("Grookey", "Field", "Grass", 87.5, 20),
            new Pokemon("Thwackey", "Field", "Grass", 87.5, 20),
            new Pokemon("Rillaboom", "Field", "Grass", 87.5, 20),
            new Pokemon("Scorbunny", "Field", "Human-Like", 87.5, 20),
            new Pokemon("Raboot", "Field", "Human-Like", 87.5, 20),
            new Pokemon("Cinderace", "Field", "Human-Like", 87.5, 20),
            new Pokemon("Sobble", "Field", "Water 1", 87.5, 20),
            new Pokemon("Drizzile", "Field", "Water 1", 87.5, 20),
            new Pokemon("Inteleon", "Field", "Water 1", 87.5, 20),
            new Pokemon("Milcery", "Fairy", "Amorphous", -100.0, 20),
            new Pokemon("Alcremie", "Fairy", "Amorphous", -100.0, 20),
            new Pokemon("Duraludon", "Mineral", "Dragon", 50.0, 30),
            new Pokemon("Kleavor", "Bug", 50.0, 20),
            new Pokemon("Overqwil", "Water 2", 50.0, 20),
            new Pokemon("Articuno", "Undiscovered", 0.0,80),
            new Pokemon("Zapdos", "Undiscovered",0.0, 80),
            new Pokemon("Moltres", "Undiscovered",0.0, 80),
            new Pokemon("Raikou", "Undiscovered", 0.0,80),
            new Pokemon("Entei", "Undiscovered",0.0, 80),
            new Pokemon("Suicune", "Undiscovered",0.0, 80),
            new Pokemon("Ho-Oh", "Undiscovered", 0.0,120),
            new Pokemon("Lugia", "Undiscovered",0.0, 120),
            new Pokemon("Latios", "Undiscovered",100.0, 120),
            new Pokemon("Latias", "Undiscovered", -100.0,120),
            new Pokemon("Kyogre", "Undiscovered",0.0, 120),
            new Pokemon("Groudon", "Undiscovered",0.0, 120),
            new Pokemon("Rayquaza", "Undiscovered", 0.0,120),
            new Pokemon("Cobalion", "Undiscovered",0.0, 80),
            new Pokemon("Terrakion", "Undiscovered",0.0, 80),
            new Pokemon("Virizion", "Undiscovered",0.0, 80),
            new Pokemon("Reshiram", "Undiscovered",0.0, 120),
            new Pokemon("Zekrom", "Undiscovered",0.0, 120),
            new Pokemon("Kyurem", "Undiscovered",0.0, 120),
            new Pokemon("Solgaleo", "Undiscovered",0.0, 120),
            new Pokemon("Lunala", "Undiscovered",0.0, 120),
            new Pokemon("Necrozma", "Undiscovered",0.0, 120),
            new Pokemon("Kubfu", "Undiscovered",87.5, 120),
            new Pokemon("Urshifu", "Undiscovered",87.5, 120),
            new Pokemon("Spectrier", "Undiscovered",0.0, 120),
            new Pokemon("Glastrier", "Undiscovered",0.0, 120),
            new Pokemon("Regirock", "Undiscovered",0.0, 80),
            new Pokemon("Regice", "Undiscovered",0.0, 80),
            new Pokemon("Registeel", "Undiscovered",0.0, 80),
            new Pokemon("Deoxys", "Undiscovered",0.0, 120),
            new Pokemon("Regigigas", "Undiscovered",0.0, 120),
            new Pokemon("Keldeo", "Undiscovered",0.0, 80),
            new Pokemon("Cosmog", "Undiscovered",0.0, 120),
            new Pokemon("Cosmoem", "Undiscovered",0.0, 120),
            new Pokemon("Meloetta", "Undiscovered",0.0, 120),
            new Pokemon("Mewtwo", "Undiscovered",0.0, 120),
            new Pokemon("Mew", "Undiscovered", 0.0,120),
            new Pokemon("Ekans", "Field", "Dragon", 50.0, 20),
            new Pokemon("Arbok", "Field", "Dragon", 50.0, 20),
            new Pokemon("Clefairy", "Fairy", 25.0, 10),
            new Pokemon("Clefable", "Fairy", 25.0, 10),
            new Pokemon("Poliwag", "Water 1", 50.0, 20),
            new Pokemon("Poliwhirl", "Water 1", 50.0, 20),
            new Pokemon("Poliwrath", "Water 1", 50.0, 20),
            new Pokemon("Bellsprout", "Grass", 50.0, 20),
            new Pokemon("Weepinbell", "Grass", 50.0, 20),
            new Pokemon("Victreebel", "Grass", 50.0, 20),
            new Pokemon("Geodude", "Mineral", 50.0, 20),
            new Pokemon("Graveler", "Mineral", 50.0, 20),
            new Pokemon("Golem", "Mineral", 50.0, 20),
            new Pokemon("Koffing", "Amorphous", 50.0, 20),
            new Pokemon("Weezing", "Amorphous", 50.0, 20),
            new Pokemon("Snorlax", "Monster", 87.5, 40),
            new Pokemon("Sentret", "Field", 50.0, 15),
            new Pokemon("Furret", "Field", 50.0, 15),
            new Pokemon("Hoothoot", "Flying", 50.0, 15),
            new Pokemon("Noctowl", "Flying", 50.0, 15),
            new Pokemon("Spinarak", "Flying", 50.0, 15),
            new Pokemon("Ariados", "Flying", 50.0, 15),
            new Pokemon("Cleffa", "Undiscovered", -75.0, 10),
            new Pokemon("Politoed", "Water 1", 50.0, 20),
            new Pokemon("Aipom", "Field", 50.0, 20),
            new Pokemon("Ambipom", "Field", 50.0, 20),
            new Pokemon("Yanma", "Bug", 50.0, 20),
            new Pokemon("Yanmega", "Bug", 50.0, 20),
            new Pokemon("Gligar", "Bug", 50.0, 20),
            new Pokemon("Gliscor", "Bug", 50.0, 20),
            new Pokemon("Slugma", "Amorphous", 50.0, 20),
            new Pokemon("Magcargo", "Amorphous", 50.0, 20),
            new Pokemon("Swinub", "Field", 50.0, 20),
            new Pokemon("Piloswine", "Field", 50.0, 20),
            new Pokemon("Mamoswine", "Field", 50.0, 20),
            new Pokemon("Poochyena", "Field", 50.0, 15),
            new Pokemon("Mightyena", "Field", 50.0, 15),
            new Pokemon("Lotad", "Water 1", "Grass", 50.0, 15),
            new Pokemon("Lombre", "Water 1", "Grass", 50.0, 15),
            new Pokemon("Ludicolo", "Water 1", "Grass", 50.0, 15),
            new Pokemon("Seedot", "Field", "Grass", 50.0, 15),
            new Pokemon("Nuzleaf", "Field", "Grass", 50.0, 15),
            new Pokemon("Shiftry", "Field", "Grass", 50.0, 15),
            new Pokemon("Nosepass", "Mineral", 50.0, 20),
            new Pokemon("Probopass", "Mineral", 50.0, 20),
            new Pokemon("Volbeat/Illumise", "Bug", "Human-Like", 50.0, 15),
            new Pokemon("Corphish", "Water 1", "Water 3", 50.0, 15),
            new Pokemon("Crawdaunt", "Water 1", "Water 3", 50.0, 15),
            new Pokemon("Feebas", "Water 1", "Dragon", 50.0, 20),
            new Pokemon("Milotic", "Water 1", "Dragon", 50.0, 20),
            new Pokemon("Duskull", "Amorphous", 50.0, 25),
            new Pokemon("Dusclops", "Amorphous", 50.0, 25),
            new Pokemon("Dusknoir", "Amorphous", 50.0, 25),
            new Pokemon("Chimecho", "Amorphous", 50.0, 25),
            new Pokemon("Munchlax", "Monster", 87.5, 40),
            new Pokemon("Chingling", "Amorphous", 50.0, 25),
            new Pokemon("Timburr", "Human-Like",  75.0, 20),
            new Pokemon("Gurdurr", "Human-Like",  75.0, 20),
            new Pokemon("Conkeldurr", "Human-Like",  75.0, 20),
            new Pokemon("Sewaddle", "Bug", 50.0, 15),
            new Pokemon("Swadloon", "Bug", 50.0, 15),
            new Pokemon("Leavanny", "Bug", 50.0, 15),
            new Pokemon("Basculin", "Water 2", 50.0, 40),
            new Pokemon("Basculegion", "Water 2", 50.0, 40),
            new Pokemon("Ducklett", "Water 1", "flying", 50.0, 20),
            new Pokemon("Swanna", "Water 1", "flying", 50.0, 20),
            new Pokemon("Litwick", "Amorphous", 50.0, 20),
            new Pokemon("Lampent", "Amorphous", 50.0, 20),
            new Pokemon("Chandelure", "Amorphous", 50.0, 20),
            new Pokemon("Mienfoo", "Field", "Human-Like", 50.0, 25),
            new Pokemon("Mienshao", "Field", "Human-Like", 50.0, 25),
            new Pokemon("Vullaby", "Flying", -100.0, 20),
            new Pokemon("Mandibuzz", "Flying", -100.0, 20),
            new Pokemon("Carbink", "Fairy", "Mineral", 0.0, 25),
            new Pokemon("Phantump", "Grass", "Amorphous", 50.0, 20),
            new Pokemon("Trevenant", "Grass", "Amorphous", 50.0, 20),
            new Pokemon("Grubbin", "Bug", 50.0, 15),
            new Pokemon("Charjabug", "Bug", 50.0, 15),
            new Pokemon("Vikavolt", "Bug", 50.0, 15),
            new Pokemon("Cutiefly", "Bug", "Fairy", 50.0, 20),
            new Pokemon("Ribombee", "Bug", "Fairy", 50.0, 20),
            new Pokemon("Jangmo-o", "Dragon", 50.0, 40),
            new Pokemon("Hakamo-o", "Dragon", 50.0, 40),
            new Pokemon("Kommo-o", "Dragon", 50.0, 40),
            new Pokemon("Cramorant", "Water 1", "Flying", 50.0, 20),
            new Pokemon("Morpeko", "Field", "Fairy", 50.0, 10),
            new Pokemon("Jirachi", "Undiscovered", 0.0, 120),
            new Pokemon("Manaphy", "Water 1", "Fairy", 0.0, 10),
            new Pokemon("Phione", "Water 1", "Fairy", 0.0, 10),
            new Pokemon("Darkrai", "Undiscovered", 0.0, 120),
            new Pokemon("Shaymin", "Undiscovered", 0.0, 120),
            new Pokemon("Pecharunt", "Undiscovered", 0.0,  20),
            new Pokemon("Terapagos", "Undiscovered", 50.0, 5),
            new Pokemon("Hydrapple", "Grass", "Dragon", 50.0, 20),
            new Pokemon("Archaludon", "Mineral", "Dragon", 50.0, 30),
            new Pokemon("Raging Bolt", "Undiscovered", 0.0, 50),
            new Pokemon("Gouging Fire", "Undiscovered", 0.0, 50),
            new Pokemon("Iron Boulder", "Undiscovered", 0.0, 50),
            new Pokemon("Iron Crown", "Undiscovered", 0.0, 50),
            new Pokemon("Iron Leaves", "Undiscovered", 0.0, 50),
            new Pokemon("Walking Wake", "Undiscovered", 0.0, 50),
            new Pokemon("Ogerpon", "Undiscovered", -100.0, 10),
            new Pokemon("Okidogi", "Undiscovered", 100.0, 120),
            new Pokemon("Munkidori", "Undiscovered", 100.0, 120),
            new Pokemon("Fezandipiti", "Undiscovered", 100.0, 120),
            new Pokemon("Poltchageist", "Mineral", "Amorphous", 0.0, 20),
            new Pokemon("Sinistcha", "Mineral", "Amorphous", 0.0, 20),
            new Pokemon("Dipplin", "Grass", "Dragon", 50.0, 20),
            new Pokemon("Uxie", "Undiscovered", 0.0, 80),
            new Pokemon("Mesprit", "Undiscovered", 0.0, 80),
            new Pokemon("Azelf", "Undiscovered", 0.0, 80),
            new Pokemon("Dialga", "Undiscovered", 0.0, 120),
            new Pokemon("Palkia", "Undiscovered", 0.0, 120),
            new Pokemon("Heatran", "Undiscovered", 50.0, 10),
            new Pokemon("Cresselia", "Undiscovered", -100.0, 120),
            new Pokemon("Arceus", "Undiscovered", 0.0, 120),
            new Pokemon("Tornadus", "Undiscovered", 100.0, 120),
            new Pokemon("Thundurus", "Undiscovered", 100.0, 120),
            new Pokemon("Landorus", "Undiscovered", 100.0, 120),
            new Pokemon("Diancie", "Undiscovered", 0.0, 25),
            new Pokemon("Hoopa", "Undiscovered",  0.0, 120),
            new Pokemon("Volcanion", "Undiscovered", 0.0, 120),
            new Pokemon("Magearna", "Undiscovered", 0.0, 120),
            new Pokemon("Perrserker", "Field", 50.0, 20),
            new Pokemon("Zacian", "Undiscovered", 0.0, 120),
            new Pokemon("Zamazenta", "Undiscovered", 0.0, 120),
            new Pokemon("Eternatus", "Undiscovered", 0.0, 120),
            new Pokemon("Zarude", "Undiscovered", 0.0, 120),
            new Pokemon("Regieleki", "Undiscovered", 0.0, 120),
            new Pokemon("Regidrago", "Undiscovered", 0.0, 120),
            new Pokemon("Zacian", "Undiscovered", 0.0, 120),
            new Pokemon("Calyrex", "Undiscovered", 0.0, 120),
            new Pokemon("Wyrdeer", "Field", 50.0, 20),
            new Pokemon("Ursaluna", "Field", 50.0, 20),
            new Pokemon("Sneasler", "Field", 50.0, 20),
            new Pokemon("Enamorus", "Undiscovered", -100.0, 20),
            new Pokemon("Quagsire", "Water 1", "Field", 50.0, 20),
    };
}
